# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: pygments
plugins: [jekyll-paginate-v2]

pagination:
  enabled: true
  per_page: 3
  permalink: "/page/:num/"

comments: true

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: Kareem Mohllal
description: "Kareem Mohllal's personal website"
keywords: "Kareem, Mohllal, personal, website, Software, Engineer, blog, web"
url: https://mohllal.github.io

google_analytics: XX-YYYYYYYY-Z
repo: http://github.com/mohllal/mohllal.github.io
disqus_shortname: "mohllal.github.io"
disqus_site_shortname: "mohllal-github-io"

# Author settings
author:
  name: Kareem Mohllal
  job: Backend Engineer
  bio: "Enthusiast performance, responsive design and usability, always looking for the best project and good coffee."
  thumb: /images/author.jpg
  email: kareem.mohllal@gmail.com
  url: https://mohllal.github.io
  github: https://github.com/mohllal
  linkedin: https://linkedin.com/in/mohllal

# navbar pages
navbar:
  - slug: about
    title: About
  - slug: blog
    title: Blog

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]
